### ISSUE TITLE
Language Selection Page

### ISSUE THREAD

**Issue by odhlen** [slavefreetrade/libertas_people#24]
Update buttons on the UI Language Selection page to match the UI for the rest of the survey.

**Comment by MichaelKMalak** [comment]
@SouvikDuttaChowdhury any updates?

**Comment by odhlen** [comment]
@MichaelKMalak would you mind reviewing this and making sure it will merge ok with the latest version in main? Thanks!

**Comment by MichaelKMalak** [comment]
@odhlen Thanks for the ping! ok, sure I will check it.. I am a bit busy today/tomorrow so I will get back to you by Wednesday if it is not v urgent.
