### ISSUE TITLE
Add a placeholder for the application license 

### ISSUE THREAD

**Issue by Jerome-Clement** [slavefreetrade/libertas_people#44]
app can not be reverse engineered, used for another purpose, ...

**Comment by MichaelKMalak** [comment]
@Jerome-Clement This issue is a bit unclear. Do you mean we should add a License file? if so, which license from these https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository.

**Comment by Jerome-Clement** [comment]
At this stage, this is adding a page, this is not about code license in github, this is a use license for workers

**Comment by MichaelKMalak** [comment]
@Jerome-Clement @andreasts when the page is added, from where should it be accessed?

**Comment by Jerome-Clement** [comment]
I see that for the first connection +being accessible as a link in the first page when coming back, like in most apps
