### ISSUE TITLE
Add a placeholder for the data privacy statements 

### ISSUE THREAD

**Issue by Jerome-Clement** [slavefreetrade/libertas_people#45]

**Comment by MichaelKMalak** [comment]
@Jerome-Clement It is a bit unclear. Do you mean adding the page to the app's UI in the about section? if so, I think there would be some UI changes.

**Comment by Jerome-Clement** [comment]
@MichaelKMalak , adding indeed a page as part of the section with the introduction pages - indeed a flow edition but minor, one more page

**Comment by MichaelKMalak** [comment]
@Jerome-Clement @andreasts Just confirming, the page is only accessible in the onboarding or will the user be able to access it from another place in the app?

**Comment by Jerome-Clement** [comment]
I see that for the first connection +being accessible as a link in the first page when coming back, like in most apps
