### ISSUE TITLE
I can't see any surveys upon building a fresh copy of the code from master branch.

### ISSUE THREAD

**Issue by SouvikDuttaChowdhury** [slavefreetrade/libertas_people#49]
During my work on language selection page, I was not able to get any survey. I thought it could have been caused because of my location so I used a VPN, but that didn't help as well.

**Comment by MichaelKMalak** [comment]
I tested it out and it is working fine. The possible cause is that you finished the surveys. Every time interval, you get a new survey and it is possible you got all of them. Try to uninstall the app from your device and install it again. If it still didn't work, I will reopen the issue.
