### ISSUE TITLE
Split repo for production app

### ISSUE THREAD

**Issue by odhlen** [slavefreetrade/libertas_people#61]
Create a production app branch and a demo app branch. Remove all demo features from app and push to production app branch. Continue to use demo app branch for demo purposes.

**Comment by MichaelKMalak** [comment]
@odhlen What are the demo features to be removed? If you can provide a comprehensive list, it would be useful.

**Comment by odhlen** [comment]
Remove select survey frequency step

<img width="457" alt="Screenshot 2021-03-19 at 09 36 41" src="https://user-images.githubusercontent.com/1123048/111760591-cb2b0c00-8896-11eb-9d73-2746c9389a54.png">

**Comment by MichaelKMalak** [comment]
Okay great.. it should be 1 month for production, right?

**Comment by MichaelKMalak** [comment]
Great, thanks! I will remove the page on prod and set it to one month then.

**Comment by MichaelKMalak** [comment]
@odhlen Instead of splitting the code base and having to maintain and make edits. What do you think of using flavors https://flutter.dev/docs/deployment/flavors ?

**Comment by odhlen** [comment]
Looks like a good solution, whatever works for you, happy to take your guidance on this.
